---
name: frontend
_package: !include "../default.yaml"
<<: *package-defaults
dependencies:
  - base
  - common
  - reflex-dom
library:
  source-dirs: src
executables:
  server:
    main: main.hs
    source-dirs: bin
    dependencies:
      - frontend
