---
name: webapp
version: 0.1.0
github: saschagrunert/webapp.hs
license: MIT
author: Sascha Grunert
maintainer: mail@saschagrunert.de
copyright: 2018 Sascha Grunert

extra-source-files:
  - README.md

synopsis: An approach in bringing yesod and miso together
category: Failure
description: Please see the README on GitHub at
  <https://github.com/saschagrunert/failure#readme>

dependencies:
  - aeson
  - base
  - bytestring
  - data-default
  - fast-logger
  - file-embed
  - http-client
  - http-client-tls
  - lens
  - monad-logger
  - template-haskell
  - wai
  - wai-extra
  - wai-logger
  - warp
  - yaml
  - yesod
  - yesod-core
  - yesod-static

ghc-options:
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-implicit-prelude
  - -Wno-missed-specialisations
  - -Wno-missing-exported-signatures
  - -Wno-missing-import-lists
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-safe
  - -Wno-unsafe

default-extensions:
  - OverloadedStrings
  - TypeFamilies
  - ViewPatterns

flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false

library:
  source-dirs: src
  when:
    - condition: (flag(dev)) || (flag(library-only))
      then:
        ghc-options:
          - -fwarn-tabs
          - -O0
        cpp-options: -DDEVELOPMENT
      else:
        ghc-options:
          - -fwarn-tabs
          - -O2

executables:
  webapp:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    dependencies:
      - webapp
    when:
      - condition: flag(library-only)
        buildable: false
