---
name: webapp-backend

_package: !include "../package-defaults.yaml"
<<: *package-defaults

dependencies:
  - base
  - webapp
  - aeson
  - bytestring
  - data-default
  - fast-logger
  - file-embed
  - http-client
  - http-client-tls
  - lens
  - monad-logger
  - template-haskell
  - wai
  - wai-extra
  - wai-logger
  - warp
  - yaml
  - yesod
  - yesod-core
  - yesod-static

flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false

library:
  source-dirs: src
  when:
    - condition: (flag(dev)) || (flag(library-only))
      then:
        ghc-options:
          - -fwarn-tabs
          - -O0
        cpp-options: -DDEVELOPMENT
      else:
        ghc-options:
          - -fwarn-tabs
          - -O2

executables:
  server:
    main: main.hs
    source-dirs: bin
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    dependencies:
      - webapp-backend
    when:
      - condition: flag(library-only)
        buildable: false
