---
static-dir: _env:YESOD_STATIC_DIR:static
host: _env:YESOD_HOST:*4
port: _env:YESOD_PORT:3000
ip-from-header: _env:YESOD_IP_FROM_HEADER:false

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# mutable-static: false
